### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by papr** [themrx/PupilCaptureCPP#1]
Hey @themrx 
My name is Pablo and I work for Pupil Labs. We have just come across your project and we think that it is a great contribution! @mattem86 has proposed to add your project to our community repository: https://github.com/pupil-labs/pupil-community/pull/5

Before we do that, I would like to ask you to rename this repository to `PupilCapture c++` or something similar that indicates that this is not the official Pupil Capture application. After doing that I will be happy to merge the above pull-request and add your project to the community contribution list.

Warm regards,
Pablo

**Comment by willpatera** [comment]
Hi @themrx any chance you would be willing to rename the repo so that it doesn't confuse members of the community? We have added a link to your project (merged the PR that @papr notes above) in our `pupil-community` repo here: https://github.com/pupil-labs/pupil-community#projects--forks

**Comment by aplopski** [comment]
Hi Will,
Sorry for my late reply. I will rename the project next week. What name would you prefer?
Best Regards,
Alexander Plopski
		
		

		
	




On Wed, Aug 1, 2018 at 11:58 AM +0500, "Will" <notifications@github.com> wrote:












Hi @themrx any chance you would be willing to rename the repo so that it doesn't confuse members of the community? We have added a link to your project (merged the PR that @papr notes above) in our pupil-community repo here: https://github.com/pupil-labs/pupil-community#projects--forks

**Comment by willpatera** [comment]
Hi @themrx - thanks for the quick reply! What do you think about `PupilCamC++` or something like this?

**Comment by aplopski** [comment]
Hi @willpatera 

I renamed it to PupilCamCPP. Let me know if this is ok.

**Comment by willpatera** [comment]
@themrx great! Thank you 😸 Please close the issue.
